### ISSUE TITLE
Upgrade the automatic calibration

### ISSUE THREAD

**Issue by timotheeg** [timotheeg/nestrischamps#28]
Make it easier for user to calibrate.

The [current calibrator](https://github.com/timotheeg/nestrischamps/blob/main/public/ocr/calibration.js) uses openCV, but that's a 8MB file to download and it's not very accurate.

Recommendation from @alex-ong [in discord](https://discordapp.com/channels/817528744565932043/817528745018654787/825014017638662195):

![image](https://user-images.githubusercontent.com/935223/112718403-ad604580-8f2d-11eb-866e-5aad9e8933b6.png)

**Comment by alex-ong** [comment]
I am hesitant to copy pasta trey's algo, but it is highly effective. Maybe we can make a similar but better one :(

**Comment by alex-ong** [comment]
```python
from PIL import Image
import numpy as np

def test():
    img = Image.open("sample.png")
    size = img.size    
    result = get_board(img)


def scan_dir(arr, y, x, func):
    while (kinda_black(arr[y][x])):
        (y, x) = func(y,x)
    return y, x
    
def scan_up(y,x):
    return y-1, x

def scan_down(y,x):
    return y+1, x
    
def scan_left(y,x):
    return y, x-1

def scan_right(y,x):
    return y, x+1        
    
def get_board(img):
    arr = np.asarray(img)    
    size = arr.shape[:2]
    centre = (size[0]//2, size[1]//2)
    
    y = centre[0]
    x = centre[1]
    
    # find left
    _, x = scan_dir(arr,y,x, scan_left)   
    left = x
    x = centre[1]
    
    # find right
    _, x = scan_dir(arr,y,x, scan_right)   
    right = x
    x = centre[1]
    
    # find top and bottom:    
    col_width = (right-left)//10
    top = centre[0]
    bot = centre[0]
    for col in range(10):
        x = left + col*col_width + col_width//2
        y, _ = scan_dir(arr, centre[0],x, scan_up)
        if y < top:
            top = y
        y, _ = scan_dir(arr, centre[0],x, scan_down)
        if y > bot:
            bot = y
            
    
    print ("left:", left)
    print ("right:", right)
    print ("top:", top)
    print ("bottom:", bot)
    
    #adjust based on blocks    
    
def kinda_black(col):
    return col[0] < 20 and col[1] < 20 and col[2] < 20
    
if __name__ == "__main__":
    test()
```

Here's a (probably) faster,  less accurate version than trey's. Instead of doing `floodfill` it does a brief scan. I will tweak this a bit to scan vertically for left/right detection too. This takes 0.1s.

**Comment by timotheeg** [comment]
Thanks @alex-ong . I implemented a full flood fill, driven by a human clicking in the black area, so I don't need to try to guess where the field is 😄
