### ISSUE TITLE
Cumulate Score Beyond maxout

### ISSUE THREAD

**Issue by timotheeg** [timotheeg/nestrischamps#62]
By knowing the lines and start_level, line clears events can be detected beyond maxout even without a Game Genie code, and score can be counted in nestrischamps past `999,999`.

Push down point past maxout can't be known obviously, but counting past maxout can be a nice addition.

This is already done to some extent since push down points are computed in the das trainer and classic layouts by comparing how much the score the players should have had after a clear with the actual score he has, and the difference are the push down points.

See the code [here](https://github.com/timotheeg/nestrischamps/blob/119c94f1f13fbeddb1cdf4e233f8bea0fe527289/public/views/Game.js#L195-L205), copied below for reference:
```javascript
onLine(event) {
	const
		num_lines    = event.lines - this.data.lines.count,
		lines_score  = this.getScore(event.level, num_lines),
		actual_score = event.score - this.data.score.current;

	// update total lines and points
	this.data.lines.count = event.lines;
	this.data.points.count = event.score;

	// update drop score
	this.data.points.drops.count += actual_score - lines_score;
```

**Comment by Torbaz** [comment]
https://github.com/timotheeg/nestrischamps/pull/66 Fixed here

**Comment by timotheeg** [comment]
Done by @Torbaz in #66 🎉
