### ISSUE TITLE
Add a game data buffer to renderers

### ISSUE THREAD

**Issue by Stabyourself** [timotheeg/nestrischamps#84]
Depending on the distance to the server for both producer and the person who uses the renderer, frames can take a very varying amount of time until they travel both distances. This causes gameplay to appear "laggy".

By buffering frames for even a short time like 1 second, rendering would be much improved with the only downside being the delay.

**Comment by timotheeg** [comment]
Thanks! I think this is the next thing I'll be working on :)

**Comment by alex-ong** [comment]
Another thing you can do is to start the games simultaneously when you get the game_start event, as well as a x second buffer (1 should be enough). This way players can't screen-cheat and copy on same-piece rom sets (this is a huge issue cheating issue)

**Comment by timotheeg** [comment]
Frame Buffer added in https://github.com/timotheeg/nestrischamps/pull/85.

Changes for a simultaneous start should be its own issue. I'll open a new one later.
